version: "3"

services:

  client: 
    build: ./
    restart: always
    ports:
      - 3001:3000
    volumes:
        - ./node_modules/:/app/node_modules/
        - ./src/:/app/src/
    container_name: ticked_client
    networks:
      - auth-net

networks:
  auth-net:
    driver: bridge