version: "3"

services:

  nats:
    image: nats-streaming:0.17.0
    command: -hbf 2 -hbt 5s -hbi 5s -p 4222 -m 8222 -SD -cid ticketing
    ports: 
      - 4222:4222
      
  queue: 
    image: redis
    ports:
      - 6379:6379
    container_name: redis-queue

  database: 
    image: mongo
    ports:
      - 27017:27017
    container_name: mongo_database
    # networks:
    #   - auth-net

  # app: 
  #   build: ./
  #   restart: always
  #   ports:
  #     - 3000:3000
  #   volumes:
  #       - ./node_modules/:/app/node_modules/
  #       - ./:/app/
  #   container_name: auth_ticked_app
  #   networks:
  #     - auth-net
  #   depends_on:
  #     - database

networks:
  auth-net:
    driver: bridge