version: "3"

services:

  app: 
    build: ./
    restart: always
    ports:
      - 3000:3000
    volumes:
        - ./node_modules/:/app/node_modules/
        - ./src/:/app/src/
    container_name: auth_ticked_app