version: "3"

services:

  database: 
    image: mongo
    ports:
      - 27017:27017
    container_name: mongo_database
    networks:
      - auth-net

  app: 
    build: ./
    restart: always
    ports:
      - 3000:3000
    volumes:
        - ./node_modules/:/app/node_modules/
        - ./src/:/app/src/
    container_name: auth_ticked_app
    networks:
      - auth-net
    depends_on:
      - database

networks:
  auth-net:
    driver: bridge